In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [15]:
lr=LogisticRegression()
svm=SVC()
rf= RandomForestClassifier()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [16]:
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9907407407407407

In [13]:
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9740740740740741

In [30]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [31]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
     print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [45]:
def get_score(model,X_train,X_test,y_train,y_test):
      model.fit(X_train,y_train)
      return model.score(X_test,y_test)

In [46]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [47]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9907407407407407

In [48]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9851851851851852

In [60]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [70]:
scores_l=[]
scores_svm=[]
scores_rf=[]

In [71]:
scores_l

[]

In [72]:
for train_index,test_index in kf.split(digits.data):
  X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index], \
                                  digits.target[train_index], digits.target[test_index]

In [73]:
scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))

C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [74]:
scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
scores_svm

[0.9549248747913188]

In [82]:
scores_rf.append(get_score(RandomForestClassifier(n_estimators=70),X_train,X_test,y_train,y_test))

In [83]:
scores_rf

[0.9282136894824707,
 0.9332220367278798,
 0.9265442404006677,
 0.9248747913188647]